name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.9.0 # Change to your desired Node.js version
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.email "avikalpgupta@gmail.com"
        git config --global user.name "Avikalp Kumar Gupta"
        git checkout --orphan gh-pages
        git rm -rf .
        git add -A
        cp -r build/. .
        git add -f -A
        git commit -m "Deploy to GitHub Pages"
        git push -f origin gh-pages
