name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your main branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.9.0 # Change to your desired Node.js version
        cache: 'npm'

    - name: Install Dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Configure Git
      run: |
        git config --global user.email "avikalpgupta@gmail.com"
        git config --global user.name "Avikalp Kumar Gupta"

    - name: Deploy to GitHub Pages
      run: |
        npm install -g gh-pages
        gh-pages -d build -b gh-pages -m "Deploy to GitHub Pages" -u "Avikalp Kumar Gupta <avikalpgupta@gmail.com>"
      env:
        GH_PAT: ${{ secrets.GH_PAT }}